### ISSUE TITLE
Not being able to make the Next JS starter work

### ISSUE THREAD

**Issue by GFier** [storyblok/custom-app-examples#7]
[storyblokurl]: https://www.storyblok.com?utm_source=github.com&utm_medium=issue-template

Hi! I am trying to make the app-nextjs-starter work. 
I followed the steps in the [readme](https://github.com/storyblok/custom-app-examples/blob/main/app-nextjs-starter/README.md). I am not sure if it's ok to use the forwarding URL from ngrok as the base_url. But to test this also deployed the starter and used the Vercel deployment link (i.e.:  https://my-storyblok-app.vercel.app) as base_url and also failed.
####  However, I found this [pr](https://github.com/storyblok/custom-app-examples/pull/6) and wanted to be sure is a config error and not the pr itself because we are using US authentication.
---

## Expected Behavior
![Screenshot 2023-05-19 at 18 53 13](https://github.com/storyblok/custom-app-examples/assets/64488427/c7af8928-8ada-4e5f-ab1b-139c94168ca6)

Work as shown in README.md
## Current Behavior

I can install the app but when click on it get redirected with error 
![Screenshot 2023-05-22 at 12 36 49](https://github.com/storyblok/custom-app-examples/assets/64488427/7ea67147-56fb-4d5c-bfda-393761c2a554)
![Screenshot 2023-05-22 at 12 35 29](https://github.com/storyblok/custom-app-examples/assets/64488427/4f45bbb7-92fb-48c1-a97a-f6e07e732bac)

## Steps to Reproduce

1. Follow readme steps.
2. Add CLIENT_ID & CLIENT_SECRET as envs from Storyblok app page.
3. Add urls in app config and to envs ![Screenshot 2023-05-19 at 19 01 06](https://github.com/storyblok/custom-app-examples/assets/64488427/25468fd1-e793-44f2-9e1e-a4c1aa5a74f1)

Thanks!! Thrilled to have a next-js starter for apps :smile:

**Comment by johannes-lindgren** [comment]
Hi @GFier, thanks for reporting this issue. There was indeed an issue with US spaces that has been resolved by the [pull request](https://github.com/storyblok/custom-app-examples/pull/6) that you referred to.

If you decide to upgrade the version on an already existing project, make sure to also make requests to Storybook's APIs with the [storyblok-js-client](https://www.npmjs.com/package/storyblok-js-client), because you will need to pass the `region` parameter in the requests.  

Sorry for the late response. If you have any feedback on this topic, we'd be happy to receive it 🙂

**Comment by GFier** [comment]
Hi @johannes-lindgren thanks for taking the time to address the issue!

I did a fresh start: clone the repo again, set it up, and test it. However, I still get an issue 

![Screenshot 2023-06-02 at 11 13 43](https://github.com/storyblok/custom-app-examples/assets/64488427/786ab02c-b637-4a74-b90c-36adb28fed45)

Tested in different browsers just to check is not a cookies issue as the error says.

Any idea what the cause of the problem could be??
